import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';
import { detectSwiftSpm, extractSwiftSpm, type SwiftSpmInfo } from './extractors/swift-spm.js';
import {
  detectTypeScriptNextjs,
  extractTypeScriptNextjs,
  type TypeScriptNextjsInfo,
} from './extractors/typescript-nextjs.js';

export type ProjectTypeInfo = SwiftSpmInfo | TypeScriptNextjsInfo;

export interface AgentIndex {
  stack: string[];
  hotFiles: HotFile[];
  invariants: Invariant[];
  projectType?: ProjectTypeInfo;
}

export interface HotFile {
  path: string;
  context: string;
}

export interface Invariant {
  text: string;
  source: string;
}

const HOT_FILE_PATTERN = /`([\w./][\w./\-]*\.\w{1,10})`/g;
const INVARIANT_PATTERNS = /\b(never|always|nunca|sempre|must|must not|Nunca|Sempre|Never|Always)\b.{10,}/gi;

function readFileSafe(path: string): string {
  if (!existsSync(path)) return '';
  return readFileSync(path, 'utf-8');
}

export function extractStack(claudeMd: string): string[] {
  const lines = claudeMd.split('\n');
  const stackIdx = lines.findIndex((l) => /^##?\s+Stack\b/i.test(l));
  if (stackIdx === -1) return [];

  const items: string[] = [];
  for (let i = stackIdx + 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line.startsWith('#')) break;
    const match = line.match(/^[-*]\s+(.+)/);
    if (match) items.push(match[1].trim());
  }
  return items;
}

export function extractHotFiles(sources: { content: string; label: string }[]): HotFile[] {
  const seen = new Set<string>();
  const result: HotFile[] = [];

  for (const { content } of sources) {
    const lines = content.split('\n');
    for (const line of lines) {
      const matches = [...line.matchAll(HOT_FILE_PATTERN)];
      for (const m of matches) {
        const path = m[1];
        if (seen.has(path)) continue;
        seen.add(path);
        // Use the surrounding text as context (strip the backtick path itself)
        const context = line.replace(/`[^`]+`/g, '').replace(/^[-*#>\s]+/, '').trim();
        result.push({ path, context: context || 'referenced in project docs' });
        if (result.length >= 15) return result;
      }
    }
  }

  return result;
}

export function extractInvariants(rulesDir: string): Invariant[] {
  if (!existsSync(rulesDir)) return [];

  const result: Invariant[] = [];
  const files = readdirSync(rulesDir).filter((f) => f.endsWith('.md'));

  for (const file of files) {
    const content = readFileSafe(join(rulesDir, file));
    const lines = content.split('\n');
    const source = basename(file, '.md');

    for (const line of lines) {
      const trimmed = line.replace(/^[-*#>\s]+/, '').trim();
      if (trimmed.length < 15) continue;
      if (INVARIANT_PATTERNS.test(trimmed)) {
        result.push({ text: trimmed, source });
      }
      // reset lastIndex for global regex
      INVARIANT_PATTERNS.lastIndex = 0;
      if (result.length >= 20) return result;
    }
  }

  return result;
}

export function buildAgentIndex(projectRoot: string): AgentIndex {
  const claudeMdPath = join(projectRoot, 'CLAUDE.md');
  const rulesDir = join(projectRoot, '.claude', 'rules');

  const claudeMd = readFileSafe(claudeMdPath);
  const rulesFiles = existsSync(rulesDir)
    ? readdirSync(rulesDir)
        .filter((f) => f.endsWith('.md'))
        .map((f) => ({ content: readFileSafe(join(rulesDir, f)), label: f }))
    : [];

  const sources = [
    { content: claudeMd, label: 'CLAUDE.md' },
    ...rulesFiles,
  ];

  const projectType = detectProjectType(projectRoot);

  return {
    stack: extractStack(claudeMd),
    hotFiles: extractHotFiles(sources),
    invariants: extractInvariants(rulesDir),
    projectType,
  };
}

function detectProjectType(projectRoot: string): ProjectTypeInfo | undefined {
  if (detectSwiftSpm(projectRoot)) return extractSwiftSpm(projectRoot) ?? undefined;
  if (detectTypeScriptNextjs(projectRoot)) return extractTypeScriptNextjs(projectRoot) ?? undefined;
  return undefined;
}

export function formatAgentIndex(index: AgentIndex, generatedBy = 'agent-index v0.1.0'): string {
  const timestamp = new Date().toISOString().slice(0, 16).replace('T', ' ') + ' UTC';
  const lines: string[] = [`# Agent Index`, '', `_Generated by ${generatedBy} — ${timestamp}_`, ''];

  if (index.stack.length > 0) {
    lines.push('## Stack', '');
    for (const item of index.stack) lines.push(`- ${item}`);
    lines.push('');
  }

  if (index.hotFiles.length > 0) {
    lines.push('## Hot Files', '');
    for (const { path, context } of index.hotFiles) {
      lines.push(`- \`${path}\` — ${context}`);
    }
    lines.push('');
  }

  if (index.invariants.length > 0) {
    lines.push('## Invariants', '');
    for (const { text, source } of index.invariants) {
      lines.push(`- ${text} _(${source})_`);
    }
    lines.push('');
  }

  if (index.projectType) {
    lines.push('## Project Type', '');
    const pt = index.projectType;
    if (pt.type === 'swift-spm') {
      lines.push(`- **Type:** Swift/SPM`);
      lines.push(`- **Package:** ${pt.packageName}`);
      if (pt.targets.length > 0) {
        lines.push(`- **Targets:**`);
        for (const t of pt.targets) lines.push(`  - \`${t.name}\` (${t.type})`);
      }
    } else if (pt.type === 'typescript-nextjs') {
      lines.push(`- **Type:** TypeScript / ${pt.framework}`);
      const scriptEntries = Object.entries(pt.scripts);
      if (scriptEntries.length > 0) {
        lines.push(`- **Scripts:**`);
        for (const [k, v] of scriptEntries) lines.push(`  - \`${k}\`: \`${v}\``);
      }
      if (pt.keyDeps.length > 0) {
        lines.push(`- **Key deps:** ${pt.keyDeps.join(', ')}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}
